logging:
  file:
    name: myapplication.log
  level:
    root: INFO
    org.springframework.web: INFO

server:
  port: 8181

management:
  security:
    enabled: false
  port: 8181
  context-path: /monitor
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name:springboot-actuator
    version:1.0

springdoc:
  show-actuator: true
  swagger-ui.use-root-path: true
  default-produces-media-type: application/json