logging:
  file:
    name: myapplication.log
  level:
    root: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8181

management:
  security:
    enabled: false
  port: 8888
  context-path: /monitor
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name:springboot-actuator
    version:1.0